# Generated by Django 2.2.17 on 2021-08-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20210716_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='https://resourcecenter.konza.go.ke/media/repoImages/Konza-Technopolis-logo.png', null=True, upload_to='avatarImages/'),
        ),
    ]
