# Generated by Django 2.2.17 on 2020-11-26 09:54

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'The module name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('Quality Assurance', 'Quality Assurance'), ('Environmental Management', 'Environmental Management'), ('Traffic Management', 'Traffic Management')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type')),
                ('notes', models.TextField(error_messages={'max_length': 'The notes is too long. Use a maximum of 2000 characters.'}, max_length=2000, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceModuleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(error_messages={'max_length': 'The reference name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='reference')),
                ('parameter', models.CharField(error_messages={'max_length': 'The parameter name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='parameter')),
                ('notes', models.TextField(error_messages={'max_length': 'The note is too long. Use a maximum of 2000 characters.'}, max_length=2000, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceModule')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(error_messages={'max_length': 'The organization name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='organization name')),
                ('notes', models.TextField(blank=True, error_messages={'max_length': 'The notes is too long. Use a maximum of 2000 characters.'}, max_length=2000, null=True, verbose_name='notes')),
                ('type', models.CharField(choices=[('Construction', 'Construction'), ('ICT', 'ICT')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecordEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, error_messages={'max_length': 'The summary is too long. Use a maximum of 5000 characters.'}, max_length=5000, null=True, verbose_name='notes')),
                ('date', models.DateField()),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecord')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReferenceRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(error_messages={'max_length': 'The requirement name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='requirement name')),
                ('notes', models.TextField(error_messages={'max_length': 'The note is too long. Use a maximum of 2000 characters.'}, max_length=2000, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceModuleReference')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRequirementAttachmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(error_messages={'max_length': 'The document name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='document name')),
                ('notes', models.TextField(error_messages={'max_length': 'The note is too long. Use a maximum of 2000 characters.'}, max_length=2000, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceReferenceRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONSTRUCTION SUPERVISING CONSULTANT’S / PROFFESSIONALS', 'CONSTRUCTION SUPERVISING CONSULTANT’S / PROFFESSIONALS'), ('CONSTRUCTION CONTRACTOR’S PERSONNEL', 'CONSTRUCTION CONTRACTOR’S PERSONNEL')], error_messages={'max_length': 'The hint is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type')),
                ('first_name', models.CharField(error_messages={'max_length': 'The first name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='first name')),
                ('other_name', models.CharField(error_messages={'max_length': 'The other name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='other name')),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('signature', jsignature.fields.JSignatureField()),
                ('designation', models.CharField(choices=[('Construction Manager', 'Construction Manager'), ('Lead Consultant', 'Lead Consultant'), ('Lead ICT Engineer', 'Lead ICT Engineer')], error_messages={'max_length': 'The designation name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='designation')),
                ('record_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecordEntry')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_document', models.CharField(error_messages={'max_length': 'The name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='name of document')),
                ('description', models.TextField(error_messages={'max_length': 'The description is too long. Use a maximum of 2000 characters.'}, max_length=2000, verbose_name='description')),
                ('type', models.CharField(choices=[('Professional Practicing licence', 'Professional Practicing licence'), ('Work Permit', 'Work Permit')], error_messages={'max_length': 'The hint is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='personnel_attachment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRequirementMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('TYPE', 'TYPE'), ('RFI', 'RFI'), ('MA', 'MA'), ('TEST RESULT', 'TEST RESULT'), ('QUANTITY', 'QUANTITY'), ('DISPOSAL', 'DISPOSAL'), ('NUMBER OF APPROVALS', 'NUMBER OF APPROVALS'), ('EXPECTED TEST RESULTS', 'EXPECTED TEST RESULTS'), ('NUMBER OF NON-APPROVALS', 'NUMBER OF NON-APPROVALS')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type')),
                ('notes', models.TextField(error_messages={'max_length': 'The note is too long. Use a maximum of 2000 characters.'}, max_length=2000, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecordEntry')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceReferenceRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRequirementAttachmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='compliance_attachment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecord')),
                ('requirement_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRequirementAttachmentDetails')),
            ],
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='compliance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecord'),
        ),
    ]
