# Generated by Django 2.2.17 on 2020-11-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancerequirementmetric',
            name='record_entry',
        ),
        migrations.RemoveField(
            model_name='personneldocument',
            name='name_of_document',
        ),
        migrations.AddField(
            model_name='compliancerequirementattachmentsubmission',
            name='record_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecordEntry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(choices=[('CONSTRUCTION SUPERVISING CONSULTANT’S / PROFFESSIONALS', 'CONSTRUCTION SUPERVISING CONSULTANT’S / PROFFESSIONALS'), ('CONSTRUCTION CONTRACTOR’S PERSONNEL', 'CONSTRUCTION CONTRACTOR’S PERSONNEL')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='ComplianceRequirementMetricSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(error_messages={'max_length': 'The note is too long. Use a maximum of 2000 characters.'}, max_length=2000, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRequirementMetric')),
                ('record_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecordEntry')),
            ],
        ),
    ]
