# Generated by Django 2.2.17 on 2020-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201130_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemodule',
            name='type',
            field=models.CharField(choices=[('Quality Assurance', 'Quality Assurance'), ('Environmental Management', 'Environmental Management'), ('Traffic Management', 'Traffic Management'), ('Health and Safety', 'Health and Safety'), ('Security Management', 'Security Management')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=12, error_messages={'max_length': 'The month is too long. Use a maximum of 200 characters.'}, max_length=20, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='compliancerequirementmetric',
            name='metric_type',
            field=models.CharField(choices=[('TYPE/QUANTITY/DISPOSAL', 'TYPE/QUANTITY/DISPOSAL'), ('RFI/MA/TEST RESULT', 'RFI/MA/TEST RESULT'), ('NUMBER OF APPROVALS/EXPECTED TEST RESULTS', 'NUMBER OF APPROVALS/EXPECTED TEST RESULTS'), ('NUMBER OF NON-APPROVALS', 'NUMBER OF NON-APPROVALS')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='compliancerequirementmetricsubmission',
            name='notes',
            field=models.TextField(blank=True, error_messages={'max_length': 'The note is too long. Use a maximum of 2000 characters.'}, max_length=20000, null=True, verbose_name='notes'),
        ),
    ]
