# Generated by Django 2.2.17 on 2020-12-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201203_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancerequirementattachmentsubmission',
            name='compliance_record',
        ),
    ]
