# Generated by Django 2.2.17 on 2020-12-04 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_compliancerequirementattachmentsubmission_compliance_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(error_messages={'max_length': 'The designation name is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='designation name')),
                ('type', models.CharField(choices=[('CONSTRUCTION SUPERVISING CONSULTANT’S / PROFFESSIONALS', 'CONSTRUCTION SUPERVISING CONSULTANT’S / PROFFESSIONALS'), ('CONSTRUCTION CONTRACTOR’S PERSONNEL', 'CONSTRUCTION CONTRACTOR’S PERSONNEL')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecord')),
            ],
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='type',
        ),
        migrations.AddField(
            model_name='personnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PersonnelDesignation'),
        ),
        migrations.AlterField(
            model_name='personneldocument',
            name='type',
            field=models.CharField(choices=[('Professional Practicing licence', 'Professional Practicing licence'), ('Work Permit', 'Work Permit'), ('Other', 'Other')], error_messages={'max_length': 'The hint is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type'),
        ),
    ]
