# Generated by Django 2.2.17 on 2020-12-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201204_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerequirementattachmentsubmission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personneldocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
