# Generated by Django 2.2.17 on 2020-12-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201205_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneldocument',
            name='description',
            field=models.TextField(blank=True, error_messages={'max_length': 'The description is too long. Use a maximum of 2000 characters.'}, max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='personneldocument',
            name='type',
            field=models.CharField(blank=True, choices=[('Professional Practicing licence', 'Professional Practicing licence'), ('Work Permit', 'Work Permit'), ('Other', 'Other')], error_messages={'max_length': 'The hint is too long. Use a maximum of 200 characters.'}, max_length=200, null=True, verbose_name='type'),
        ),
    ]
