# Generated by Django 2.2.17 on 2020-12-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_compliancerequirementissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerequirementissue',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceReferenceRequirement'),
        ),
    ]
