# Generated by Django 2.2.17 on 2020-12-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201214_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerequirementissue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
