# Generated by Django 2.2.17 on 2020-12-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_compliancerequirementissue_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePesonnelIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, error_messages={'max_length': 'The note is too long. Use a maximum of 2000 characters.'}, max_length=20000, null=True, verbose_name='notes')),
                ('is_resolved', models.BooleanField(default=False, error_messages={}, max_length=200, verbose_name='is resolved')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceRecordEntry')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Personnel')),
            ],
        ),
    ]
