# Generated by Django 2.2.17 on 2020-12-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201219_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneldesignation',
            name='is_extra',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is extra'),
        ),
    ]
