# Generated by Django 2.2.17 on 2020-12-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_personneldesignation_is_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecordentry',
            name='project_name',
            field=models.CharField(blank=True, error_messages={'max_length': 'The name is too long. Use a maximum of 200 characters.'}, max_length=200, null=True, verbose_name='project_name'),
        ),
        migrations.AddField(
            model_name='compliancerecordentry',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('acknowledged', 'acknowledged'), ('rejected', 'rejected')], default='draft', error_messages={'max_length': 'The month is too long. Use a maximum of 20 characters.'}, max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=12, error_messages={'max_length': 'The month is too long. Use a maximum of 20 characters.'}, max_length=20, verbose_name='month'),
        ),
    ]
