# Generated by Django 2.2.17 on 2020-12-28 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_entryinheritance'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecordentry',
            name='report_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
