# Generated by Django 2.2.17 on 2021-01-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201228_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecord',
            name='submission_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=1, error_messages={'max_length': 'The month is too long. Use a maximum of 20 characters.'}, max_length=20, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='compliancerequirementmetric',
            name='metric_type',
            field=models.CharField(choices=[('TYPE', 'TYPE'), ('QUANTITY', 'QUANTITY'), ('DISPOSAL', 'DISPOSAL'), ('Request For Information (RFI)', 'Request For Information (RFI)'), ('Material Approval (MA)', 'Material Approval (MA)'), ('TEST RESULT', 'TEST RESULT'), ('NUMBER OF APPROVALS/EXPECTED TEST RESULTS', 'NUMBER OF APPROVALS/EXPECTED TEST RESULTS'), ('NUMBER OF NON-APPROVALS', 'NUMBER OF NON-APPROVALS')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personneldesignation',
            name='type',
            field=models.CharField(blank=True, choices=[('CONSTRUCTION SUPERVISING CONSULTANT’S PROFFESSIONALS', 'CONSTRUCTION SUPERVISING CONSULTANT’S PROFFESSIONALS'), ('CONSTRUCTION CONTRACTOR’S PERSONNEL', 'CONSTRUCTION CONTRACTOR’S PERSONNEL')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, null=True, verbose_name='type'),
        ),
        migrations.AlterUniqueTogether(
            name='entryinheritance',
            unique_together={('parent', 'child')},
        ),
    ]
