# Generated by Django 2.2.17 on 2020-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201228_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerequirementmetric',
            name='metric_type',
            field=models.CharField(choices=[('TYPE', 'TYPE'), ('QUANTITY', 'QUANTITY'), ('DISPOSAL', 'DISPOSAL'), ('Request For Information (RFI)', 'Request For Information (RFI)'), ('Material Approval (MA)', 'Material Approval (MA)'), ('TEST RESULT', 'TEST RESULT'), ('NUMBER OF APPROVALS/EXPECTED TEST RESULTS', 'NUMBER OF APPROVALS/EXPECTED TEST RESULTS'), ('NUMBER OF NON-APPROVALS', 'NUMBER OF NON-APPROVALS')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personneldesignation',
            name='type',
            field=models.CharField(blank=True, choices=[('CONSTRUCTION SUPERVISING CONSULTANT’S PROFFESSIONALS', 'CONSTRUCTION SUPERVISING CONSULTANT’S PROFFESSIONALS'), ('CONSTRUCTION CONTRACTOR’S PERSONNEL', 'CONSTRUCTION CONTRACTOR’S PERSONNEL')], error_messages={'max_length': 'The type is too long. Use a maximum of 200 characters.'}, max_length=200, null=True, verbose_name='type'),
        ),
        migrations.AlterUniqueTogether(
            name='entryinheritance',
            unique_together={('parent', 'child')},
        ),
    ]
