# Generated by Django 2.2.17 on 2021-01-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_contractorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorprofile',
            name='type',
        ),
    ]
