# Generated by Django 2.2.17 on 2021-01-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_contractorprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecordentry',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='summary',
            field=models.TextField(blank=True, error_messages={'max_length': 'The summary is too long. Use a maximum of 5000 characters.'}, max_length=5000, null=True, verbose_name='summary'),
        ),
    ]
