# Generated by Django 2.2.17 on 2021-01-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201230_1114'),
        ('app', '0026_auto_20210118_0953'),
    ]

    operations = [
    ]
