# Generated by Django 2.2.17 on 2021-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210118_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecordentry',
            name='review',
            field=models.TextField(blank=True, error_messages={'max_length': 'The review is too long. Use a maximum of 5000 characters.'}, max_length=5000, null=True, verbose_name='Review'),
        ),
    ]
