# Generated by Django 2.2.17 on 2021-01-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_compliancerecordentry_review'),
        ('app', '0027_merge_20210121_1332'),
    ]

    operations = [
    ]
