# Generated by Django 3.2 on 2021-05-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210211_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=5, error_messages={'max_length': 'The month is too long. Use a maximum of 20 characters.'}, max_length=20, verbose_name='month'),
        ),
    ]
