# Generated by Django 2.2.17 on 2021-08-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210607_1217'),
        ('app', '0031_auto_20210607_1319'),
    ]

    operations = [
    ]
