# Generated by Django 2.2.17 on 2021-08-25 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0032_merge_20210825_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_uid', models.CharField(blank=True, error_messages={'max_length': 'The inspection uid is too long. Use a maximum of 200 characters.'}, max_length=200, null=True, verbose_name='inspection_uid')),
                ('observation', models.TextField(blank=True, default='[UNSPECIFIED]', error_messages={'max_length': 'Your observation is too long. Use a maximum of 20000 characters.'}, max_length=20000, verbose_name='observation')),
                ('action', models.TextField(blank=True, default='[UNSPECIFIED]', error_messages={'max_length': 'Your action statement is too long. Use a maximum of 20000 characters.'}, max_length=20000, verbose_name='action')),
                ('coordinates', models.TextField(blank=True, default='[UNSPECIFIED]', error_messages={'max_length': 'Your action statement is too long. Use a maximum of 20000 characters.'}, max_length=20000, null=True, verbose_name='coordinates')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_TEAM_LEADER_REVIEW', 'PENDING_TEAM_LEADER_REVIEW'), ('PENDING_MANAGER_REVIEW', 'PENDING_MANAGER_REVIEW'), ('PUBLISHED', 'PUBLISHED'), ('COMPLIED', 'COMPLIED'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED')], default='DRAFT', error_messages={'max_length': 'The comment type  is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='comment_type')),
                ('is_resolved', models.BooleanField(default=False, error_messages={}, max_length=200, verbose_name='is resolved')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_team_lead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compliancerecordentry',
            name='is_published_with_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerequirementattachmentsubmission',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerequirementattachmentsubmission',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerequirementmetricsubmission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='block_reason',
            field=models.TextField(blank=True, error_messages={'max_length': 'The block_reason is too long. Use a maximum of 2000 characters.'}, max_length=2000, null=True, verbose_name='block reason'),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personnel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personneldesignation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personneldeg_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personneldesignation',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personneldeg_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=8, error_messages={'max_length': 'The month is too long. Use a maximum of 20 characters.'}, max_length=20, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='compliancerequirementattachmentsubmission',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancerequirementmetricsubmission',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personneldocument',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_person_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InspectionVideoEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspectionVideo/', verbose_name='video url')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, error_messages={'max_length': 'The caption is too long. Use a maximum of 2000 characters.'}, max_length=2000, null=True, verbose_name='caption')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionPhotoEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='inspectionImages/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, error_messages={'max_length': 'The caption is too long. Use a maximum of 2000 characters.'}, max_length=2000, null=True, verbose_name='caption')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(error_messages={'max_length': 'Your observation is too long. Use a maximum of 20000 characters.'}, max_length=20000, verbose_name='comment')),
                ('comment_type', models.CharField(choices=[('MEMBER', 'MEMBER'), ('TEAM_LEADER', 'TEAM_LEADER'), ('MANAGER', 'MANAGER'), ('CHIEF_MANAGER', 'CHIEF_MANAGER'), ('CONTRACTOR', 'CONTRACTOR')], default='MEMBER', error_messages={'max_length': 'The comment type  is too long. Use a maximum of 200 characters.'}, max_length=200, verbose_name='comment_type')),
                ('is_reviewer_comment', models.BooleanField(default=False)),
                ('is_teamleader_comment', models.BooleanField(default=False)),
                ('is_manager_comment', models.BooleanField(default=False)),
                ('is_contractor_comment', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ContractorProfile'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_evaluated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceModule'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ComplianceModuleReference'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_submitted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
