# Generated by Django 2.2.17 on 2021-09-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0033_auto_20210825_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerecordentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=9, error_messages={'max_length': 'The month is too long. Use a maximum of 20 characters.'}, max_length=20, verbose_name='month'),
        ),
        migrations.CreateModel(
            name='InspectionDocumentEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspectionDocument/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, error_messages={'max_length': 'The caption is too long. Use a maximum of 2000 characters.'}, max_length=2000, null=True, verbose_name='caption')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionContractorEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspectionContractorEvidence/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, error_messages={'max_length': 'The caption is too long. Use a maximum of 2000 characters.'}, max_length=2000, null=True, verbose_name='caption')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
